name: Deploy Integration to AWS Lambda

on: 
  workflow_dispatch:
    inputs:
      integration_name:
        type: choice
        description: 'Integration Name' 
        required: true
        options:
          - stripe
          - fastspring
      function_name:
        type: choice
        description: 'AWS Lambda Function Name' 
        required: true
        options:
          - stripeIntegrationDev
          - fastspringIntegrationDev
          - fabcadStripeIntegration
          - supmanfastspringInteggration

jobs:
  deploy:
    name: Build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build:${{ github.event.inputs.integration_name }}:aws

      - name: Zip lambda bundle
        run: zip -qq -r bundle.zip dist

      # 🔹 Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # 👈 change if needed

      - name: Deploy Lambda Function (create or update)
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ${{ github.event.inputs.function_name }}
          code-artifacts-dir: dist
          runtime: nodejs22.x
          handler: index.handler

