name: Deploy AWS Lambda

on: 
  workflow_dispatch:
    inputs:
      payment-platform:
        description: 'The payment platform to be integrated with'
        required: true
        default: 'stripe'
        type: choice
        options:
          - stripe
          - fastspring

jobs:
  deploy:
    name: Build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build:${{ github.event.inputs.payment-platform }}:aws

      - name: Zip lambda bundle
        run: zip -qq -r bundle.zip dist

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: my-lambda-function
          zip-file: bundle.zip   # 👈 use the zip you just created
