name: Deploy AWS Lambda

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionRole
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build:stripe:aws   # or fastspring depending on input

      - name: Zip Lambda bundle
        run: zip -qq -r -j bundle.zip dist

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: my-lambda-function
          code-artifacts-dir: ./dist
          runtime: nodejs22.x
          handler: index.handler
          role: arn:aws:iam::116976060316:role/lambda-execution-role
